### Creates new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "xyz4",
  "address": "123 main street4",
  "email": "xyz@xyz.com43",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "1995-09-09"
}

###